FROM "gitlab/gitlab-ce:latest"
WORKDIR /gitlabwd
USER root
VOLUME ["/opt/automation/gitlab/config:/etc/gitlab", "/opt/automation/gitlab/logs:/var/log/gitlab", "/opt/automation/gitlab/data:/var/opt/gitlab"]


